In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets

In [3]:
iris_X, iris_y = datasets.load_iris(as_frame=True, return_X_y=True)

In [4]:
iris_y.unique()

array([0, 1, 2])

In [5]:
iris_X.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [4]:
iris_y.unique()

array([0, 1, 2])

In [8]:
iris_X.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [9]:
iris_X['sepal length (cm)'] += 1

In [11]:
iris_X.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [13]:
copy_iris = iris_X.copy()

In [14]:
copy_iris.columns = ['Sepal_length', 'Sepal_width', 'Petal_Length', 'Petal_width']

In [15]:
copy_iris.head()

Sepal_length  Sepal_width  Petal_Length  Petal_width
0           6.1          3.5           1.4          0.2
1           5.9          3.0           1.4          0.2
2           5.7          3.2           1.3          0.2
3           5.6          3.1           1.5          0.2
4           6.0          3.6           1.4          0.2

In [17]:
iris_y.dtype

dtype('int32')

In [18]:
iris_y.astype('int8')

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int8

In [19]:
data = copy_iris.drop(['Sepal_length'], axis=1)

In [20]:
data.dropna()

Sepal_width  Petal_Length  Petal_width
0            3.5           1.4          0.2
1            3.0           1.4          0.2
2            3.2           1.3          0.2
3            3.1           1.5          0.2
4            3.6           1.4          0.2
..           ...           ...          ...
145          3.0           5.2          2.3
146          2.5           5.0          1.9
147          3.0           5.2          2.0
148          3.4           5.4          2.3
149          3.0           5.1          1.8

[150 rows x 3 columns]

In [7]:
a = np.arange(1, 21)

In [8]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [9]:
b = np.random.rand(20,20)

In [10]:
a.shape

(20,)

In [12]:
b.shape

(20, 20)

In [13]:
c = np.random.randn(2, 15)

In [14]:
c.shape

(2, 15)

In [15]:
c.transpose().shape

(15, 2)

In [16]:
np.matmul(a, b).shape

(20,)

In [17]:
(a @ b).shape

(20,)